module.exports = {
    id:1,
    is_italic:1,
    is_url:1,
    hits:100,
    is_passed:1,
    is_ontop:1,
    is_recommended:1,
    is_specials:1,
    user_id:1,
    title:"我是文章测试标题",
    article_keywords:"我是文章关键词",
    keywords:"我是SEO关键词",
    description:"我是SEO描述",
    author:"作者",
    link_url:"http://www.v5soft.com",
    template:"article/view.html",
    default_pic_url:"http://www.v5soft.com/photo.jpg",
    file_name:"index.html",
    property:"1,2,3",
    short_content:"我是文章简单描述",
    content:"我是文章内容",
    create_time:"2018-10-10 11:11:11",
    update_time:"2018-10-10 11:11:11",
    more_photo:"http://www.v5soft.com/photo.jpg",
    read_point:1000,
    tags:"文章,列表",
    classid:1,
    title_color:"#fff000",
    topic_classids:"1,2,3",
    copyfrom:"站内",
    admin_id:1,
    user_roleid:"1,3",
}